/*********************************************************
 *********************************************************
 **   DO NOT EDIT                                       **
 **                                                     **
 **   THIS FILE HAS BEEN GENERATED AUTOMATICALLY         **
 **   BY UPA PORTABLE GENERATOR                         **
 **   (c) vpc                                           **
 **                                                     **
 *********************************************************
 ********************************************************/



namespace Net.TheVpc.Upa
{

    /**
     * AccessLevel defines access level for field manipulation and retrieval. Default value is PUBLIC.
     * For each field, an insertAccessLevel, updateAccessLevel and readAccessLevel are defined.
     * <p>
     * Public access level means that every end used should have the ability
     * to modify/query the field (for insertion, for update or for retrieval)
     * This is most likely the very usual case
     * </p>
     * <p>
     * Protected access level means that only application should have the ability to modify/query the field (for insertion, for update or for retrieval)
     * This is most likely when the field is created by developer but should not be "used" by end users
     * </p>
     * <p>
     * Private access level means that only ORM (UPA Framework or one of its extensions) should have the ability to modify/query the field (for insertion, for update or for retrieval).
     * This is most likely when the field is generated by the ORM
     * </p>
     * <p>
     * Default access level is a synonym  of PUBLIC access level.
     * Particularly when used in @Field annotation, the default value is ignored and older value is retained.
     * </p>
     *
     * @author Taha BEN SALAH <taha.bensalah@gmail.com>
     */
    public enum AccessLevel {

        /**
             * Default access level is a synonym  of READ_WRITE access level.
             * Particularly when used in @Field annotation, the default value is ignored and older value is retained.
             */
        DEFAULT, /**
             * Inaccessible access level means the field is invisible to end user
             */
        INACCESSIBLE, /**
             * Read only field
             */
        READ_ONLY, /**
             * Full Access Field
             */
        READ_WRITE
    }
}
